image: robertcnelson/debian-bullseye-slim-linux-compile:latest

variables:
  KDIR: "/beaglekernel"
  ARCH: "arm64"
  CROSS_COMPILE: "/usr/bin/aarch64-linux-gnu-"

build:
  tags:
  - docker-amd64
  stage: build
  before_script:
    - CORES=$(getconf _NPROCESSORS_ONLN)
    - git clone https://git.beagleboard.org/beagleboard/linux.git -b v5.10.168-ti-arm64-r103 --depth 1 $KDIR
    - cd $KDIR
    - make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE bb.org_defconfig
    - make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j${CORES} headers_install
  script:
    - CORES=$(getconf _NPROCESSORS_ONLN)
    - cd $CI_PROJECT_DIR
    - make ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE KDIR=$KDIR -j${CORES}
