image: beagle/kernel-build-env:latest

variables:
  KVER: "5.10.168-ti-arm64-r103"

build:
  tags:
  - aarch64
  stage: build
  before_script:
    - apt update
    - apt install -y linux-headers-$KVER
  script:
    - cd $CI_PROJECT_DIR
    - make -C /usr/src/linux-headers-${KVER} KDIR=/lib/modules/${KVER}/build M=$(pwd)
    - make -C /usr/src/linux-headers-${KVER} KDIR=/lib/modules/${KVER}/build M=$(pwd) INSTALL_MOD_PATH=$(pwd)/build modules_install
  artifacts:
    paths:
      - build
